### ISSUE TITLE
prebuild cargo is using openssl 1.1

### ISSUE THREAD

**Issue by xlc** [koute/rustc-rv32e#4]
Getting this error when try to build example with [this](https://github.com/koute/polkavm/blob/master/guest-programs/build-examples.sh)
```
/home/bryan/.rustup/toolchains/riscv32em-nightly-2024-01-05-r0-x86_64-unknown-linux-gnu/bin/cargo: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
```

I need to instal openssl 1.1, which is deaerated and setup `LD_LIBRARY_PATH` to get it working

**Comment by koute** [comment]
Opened: https://github.com/paritytech/rustc-rv32e-toolchain/issues/25
